## @@@@@@@@@@@@@@@@@@@@@@
## Flashfocus config file
## @@@@@@@@@@@@@@@@@@@@@@

# Opacity of window during flash.
flash-opacity: 0.8

# Windows are restored to this opacity value at the end of a flash.
default-opacity: 1

# Length of flash in milliseconds.
time: 500

# If true, flashes are not faded out. This will improve performance but flashes
# won't be smooth.
simple: false

# Number of animation frames in a flash.
ntimepoints: 10

# Set this to False if you don't want windows to flash on focus.
flash-on-focus: true

# Whether or not to flash windows if they are the only window on the desktop.
# Possible values:
#   'always':
#      Always flash lone windows
#   'never':
#      Never flash lone windows
#   'on_open_close':
#      Lone windows will be flashed only if a) if they were just opened and b) if 
#      another window was just closed. 
#   'on_switch':
#      Lone windows will be flashed only upon switching desktops.
flash-lone-windows: 'always'

# Defining window-specific flash rules
#
# Flash rules are defined by matching the WM_CLASS property of a window.
# To get the WM_CLASS property of a window use 'xprop WM_CLASS' and click on a
# window. The property is a tuple of the form (window-id, window-class). The
# window-class is usually the name of the application, but not always.
#
# Say I'd like to set all 'termite' windows to 80% opacity but leave other
# windows at full opacity:
#
# rules:
#   - window-class: Termite
#     default-opacity: 0.8
#
#
# I also would prefer that firefox windows are not flashed on focus:
#
# rules:
#   - window-class: Firefox
#     flash-on-focus: False
#   - window-class: Termite
#     default-opacity: 0.8
#
#
# For more complicated rules, you can use (python-style) regexes:
#
# rules:
#   - window-id: ^(?!termite)$
#     default-opacity: 0.8
