## @@@@@@@@@@@@@@@@@@@@@@
## Flashfocus config file
## @@@@@@@@@@@@@@@@@@@@@@

# Opacity of window during flash.
flash-opacity: 0.8

# Windows are restored to this opacity value at the end of a flash.
default-opacity: 1

# Length of flash in milliseconds.
time: 500

# If true, flashes are not faded out. This will improve performance but flashes
# won't be smooth.
simple: false

# Number of animation frames in a flash.
ntimepoints: 10
